#include <gtest/gtest.h>
#include "Player.h"
#include "Enemy.h" // Include the full definition of Enemy to fix the unique_ptr destructor error
#include "common.h"
#include <vector>
#include <memory>

TEST(PlayerBehaviorTest, HealthRegeneratesOverTime) {
    // 1. Setup
    GameSettings settings;
    settings.playerHealth = 100;
    settings.healthRegenRate = 10; // 10 HP per second
    settings.healthRegenDelay = 3.0f;

    Player player(settings);

    // Manually set the player's health lower to test regeneration
    player.health = 50;

    // Empty list of enemies for this test
    std::vector<std::unique_ptr<Enemy>> no_enemies;

    // Simulate taking a hit to reset the regeneration timer
    player.lastAttackClock.restart();

    float deltaTime = 0.1f;

    // 2. Action
    // Wait for the regeneration delay period, during which no health should be gained
    for (float totalTime = 0; totalTime < settings.healthRegenDelay; totalTime += deltaTime) {
        player.update(deltaTime, settings, no_enemies);
    }

    // Health should not have changed yet
    ASSERT_FLOAT_EQ(player.health, 50.f);

    // Now, wait for one more second, during which health should regenerate
    for (float totalTime = 0; totalTime < 1.0f; totalTime += deltaTime) {
        player.update(deltaTime, settings, no_enemies);
    }

    // 3. Assert
    // After 1 second of regeneration at 10 HP/sec, health should be 60.
    EXPECT_NEAR(player.health, 60.f, 1.f)
        << "Player health should have regenerated by roughly 10 points after the delay.";

    // Let's continue for another second
    for (float totalTime = 0; totalTime < 1.0f; totalTime += deltaTime) {
        player.update(deltaTime, settings, no_enemies);
    }

    EXPECT_NEAR(player.health, 70.f, 1.f)
        << "Player health should continue to regenerate.";
}
